dev_lite:
  DB_USAGE: sqlite:///server/usages.db
  DB_GAMES: sqlite:///server/langman.db

dev_postgres:
  DB_USAGE: sqlite:///server/usages.db
  DB_GAMES: postgresql:///langman

# install postgres
# switch user: `sudo -u postgres -i`
# create superuser ed : `createuser --interactive`
# exit

heroku:
  DB_USAGE: sqlite:///server/usages.db
  DB_GAMES: env:DATABASE_URL